added performance metrics of fine-grained ner
centre-for-humanities-computing/DaCy pull request #252
Opened 2023-04-29 08:50 UTC by emiltj

2023-04-29 20:39 UTC, KennethEnevoldsen requested changes
Looking good so far, but there is some information missing. Let me know if the pointers are understandable.

I do the like plots with the dots as well. I would love to add those as well?

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/_static/ner_fine_grained_domain_perf.png
Hmm, the header here is a bit odd. Is it like the model category or the framework? NbAI-Lab, at least, does not seem to fit into the category.

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/_static/ner_fine_grained_domain_perf.png
An alternative is to replace it with ScandiNER or Dan Sattrup Nielsen

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
I would create a new section called robustness across domains instead of using this existing section.

Then add few lines on that that means as well. I also see that some of the header is the """" to denote headers I think that will cause a problem in the ordering. I would actually recommend that you just use markdown (.md). They work just fine and they are easier to maintain (and easier for contributors to edit as well).

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
Or alternatively move the entire NER section and just create a section called Performance > Named entity recognition. Where the first section is *Generalization across domain* and the second is *robustness and biases* where you can simply copy from this section.

I will make sure to fix the other sections up as well.

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/_static/ner_fine_grained_domain_perf.png
Can you change the table to use 2 decimals and remove Dannet? Will also upload the CSV for the dataset as well? Under docs/performance (nice to have if I want to recreate visualizations in the figure).

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/_static/ner_tags_fine_grained_perf.png
Can you make it 2 decimals and create an average at the bottom?

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/_static/ner_tags_fine_grained_perf.png
Ideally I would want it such that it was small medium large rather than large medium small

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
> +
```suggestion
```
I would make it *Named Entity Recognition* and *Fine-grained Named Entity Recognition*

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
> +DaCy fine-grained on the DANSK dataset
see above comment. Move DANSK to body text

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
> +  :alt: NER performance of DaCy fine-grained on the domains of the DANSK dataset
This should be moved up to the non-fine-grained section

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
> +to make DANSK match the CoNLL-2003 standards that the other models base their predictions on.
Add an info box on this describing how it is done.

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
> +In the following two tables we see the performance on named entity recognition (NER) on the DANSK dataset
link to DANSK

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/_static/ner_tags_fine_grained_perf.png
Ideally I would also want a top header above the models called F1

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
> +while the second table shows the F1-scores on the different domains within the dataset.
Can you please describe the type of F1 (micro/macro)

2023-04-29 20:39 UTC, KennethEnevoldsen commented on docs/performance.robustness.rst
> +We have highlighted the best scores in bold and second best are underlined.
```suggestion
We have highlighted the best scores in bold and second best are in italics.
```

2023-04-30 07:27 UTC, emiltj commented
@KennethEnevoldsen Great feedback!

I fixed what I understood and could. Would there be any chance that you might have time to look into the remaining?

2023-05-01 04:03 UTC, KennethEnevoldsen reviewed
Sure thing I can take a look at structuring it. If you send the data files for the plots I was also thinking of playing around with some interactive plots as well

2023-05-01 09:28 UTC, emiltj commented on docs/performance/ner_fine_grained_tag_performance.tgn
Whoops - wrong file. I uploaded the .csv instead.

2023-05-01 09:29 UTC, emiltj commented on docs/performance/sota_domain_performance.csv
I also uploaded .csv's with information on documents and texts and ents for all partitions, now.

2023-05-15 02:44 UTC, merged