loosen requirements
centre-for-humanities-computing/DaCy pull request #76
Opened 2021-11-09 09:31 UTC by dhpollack

The requirements of this package are unnecessarily strict.  Specifically, I am having issues with tqdm. I have a more in-depth explaination in the issue that I create centre-for-humanities-computing/DaCy#75.  There are also a few optimizations to your setup.py file.  I notice that the requirements.txt file is not used, which could cause a mismatch when doing `pip install -r requirements.txt` and `pip install .`

2021-11-09 13:25 UTC, KennethEnevoldsen commented
Hei @dhpollack sorry I missed this. I have debated the use of requirements.txt and setup being split up. I notice that other libraries keep these split up indicating that requirements also include packages for running the test suite. We, however, haven't done this so far so will change this according to your changes.

2021-11-09 13:41 UTC, dhpollack commented
> Hei @dhpollack sorry I missed this. I have debated the use of requirements.txt and setup being split up. I notice that other libraries keep these split up indicating that requirements also include packages for running the test suite. We, however, haven't done this so far so will change this according to your changes.

I actually ran into an error when running this and just used your version.  But my issue was with importing `__version__` instead of the way you are doing it.  The issue was that loading the version also loaded `__init__.py` which loads a bunch of modules before they are installed.  The simplest solution would be to directly load those modules instead of putting them in the `__init__.py` but that does change the user-friendliness of the library a little bit.

2021-11-09 14:46 UTC, KennethEnevoldsen requested changes

2021-11-09 14:46 UTC, KennethEnevoldsen commented on setup.py
> +    requirements = [l.strip() for l in f]
```suggestion
    requirements = f.read().split("\n")
```

2021-11-09 15:49 UTC, KennethEnevoldsen commented on setup.py
> +from dacy.about import __version__
```suggestion
with open("dacy/about.py") as f:
     v = f.read()
     for l in v.split("\n"):
         if l.startswith("__version__"):
             __version__ = l.split('"')[-2]
```

2021-11-10 08:30 UTC, KennethEnevoldsen reviewed
fixed indentation

2021-11-10 08:30 UTC, KennethEnevoldsen commented on setup.py
> +             __version__ = l.split('"')[-2]
```suggestion
    v = f.read()
    for l in v.split("\n"):
        if l.startswith("__version__"):
            __version__ = l.split('"')[-2]
```

2021-12-19 21:32 UTC, KennethEnevoldsen commented
Sorry for the late response on this @dhpollack, seems like there has been an update in one of the workflow packages (nothing wrong with DaCy). I have just updated the workflow scripts in #80 will merge this as soon as that one is done. Enjoy the holidays.

2021-12-27 21:54 UTC, KennethEnevoldsen commented
@dhpollack I have merged these changes in #82 into the dev branch along with a few other PRs related to GitHub workflow to merge a conflict before committing it to the main branch.

Thanks again for the addition sorry for the late results. Wanted to do an overhaul of the Github actions which ended up taking longer than expected.

Enjoy the holidays 🎄

2021-12-27 21:54 UTC, closed without merging